# Generated by Django 5.0.2 on 2024-03-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=22)),
                ('password2', models.CharField(max_length=12)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('Applicationdate', models.CharField(max_length=6, null=True)),
                ('area', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('postalcode', models.CharField(max_length=6, null=True)),
                ('state', models.CharField(max_length=25)),
                ('anum', models.IntegerField()),
                ('vid', models.CharField(max_length=25)),
                ('schemes', models.CharField(max_length=10, null=True)),
                ('gender', models.BooleanField()),
                ('cb1', models.BooleanField(max_length=21)),
                ('cb2', models.BooleanField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
