# Generated by Django 5.0.2 on 2024-03-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=25, null=True)),
                ('email', models.CharField(max_length=11, null=True)),
                ('msg', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=25, null=True)),
                ('username', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=6, null=True)),
                ('vehicalnumber', models.IntegerField()),
                ('vehicalname', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=6, null=True)),
            ],
        ),
    ]
