# Generated by Django 5.0.2 on 2024-03-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_contact_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='city',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
