# Generated by Django 5.0.2 on 2024-03-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_alter_registration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password2',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
