# Generated by Django 5.0.2 on 2024-03-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0008_alter_registration_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='gender',
        ),
    ]
