# Generated by Django 5.0.2 on 2024-03-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_remove_registration_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=25, null=True)),
                ('username', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=6, null=True)),
                ('vehicalnumber', models.IntegerField()),
                ('vehicalname', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='cb1',
            field=models.BooleanField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='cb2',
            field=models.BooleanField(max_length=6, null=True),
        ),
    ]
