# Generated by Django 5.0.2 on 2024-03-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0010_record_alter_registration_cb1_alter_registration_cb2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='vehicalnumber',
            new_name='vnum',
        ),
        migrations.RemoveField(
            model_name='record',
            name='vehicalname',
        ),
        migrations.AddField(
            model_name='record',
            name='vname',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
