# Generated by Django 5.0.2 on 2024-03-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0011_rename_vehicalnumber_record_vnum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='cb1',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='cb2',
            field=models.BooleanField(null=True),
        ),
    ]
