# Generated by Django 5.0.2 on 2024-03-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0012_registration_gender_alter_registration_cb1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(default=True, max_length=6),
        ),
    ]
