# Generated by Django 5.0.2 on 2024-03-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0013_alter_registration_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='AccidentType',
            field=models.CharField(max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='RoadFeatures',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='SpeedLimit',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='accidentspot',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='area',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='location',
            field=models.CharField(max_length=23, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='physicaldivider',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='rname',
            field=models.CharField(max_length=23, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='rnumber',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='roadtype',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='typeofcollision',
            field=models.CharField(max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='typeofwhether',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
