# Generated by Django 5.0.2 on 2024-03-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0016_alter_report_injury'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='complain',
        ),
    ]
