# Generated by Django 5.0.2 on 2024-03-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0017_remove_report_complain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='accidentspot',
        ),
        migrations.RemoveField(
            model_name='record',
            name='location',
        ),
        migrations.RemoveField(
            model_name='record',
            name='username',
        ),
        migrations.RemoveField(
            model_name='report',
            name='injury',
        ),
    ]
